//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Modern Frame supporting theming such as Blur styles, Acrylic style, Dark/Light mo" +
    "des for Xamarin.Forms (Android, iOS, UWP).")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("MaterialFrame")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2021")]
[assembly: System.Reflection.AssemblyFileVersion("1.3.0")]
[assembly: System.Reflection.AssemblyVersion("1.3.0")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.MaterialFrame.macOS")]


